# Publish a source directory from this repo into a target directory in a target repo

name: Copy to target repo

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

env:
  TARGET_REPO: the-dataface/yea-site
  TARGET_BRANCH: master
  TARGET_DIR: src/assets/cmsvelte/q22022
  SOURCE_DIR: build
  NODE_VERSION: lts/gallium
  BUILD_COMMAND: npm run build

jobs:
  build_and_copy:
    name: Build production files + copy to target repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: source/package-lock.json

      - name: Build production files
        run: |
          cd source
          npm ci
          ${{ env.BUILD_COMMAND }}
          cd ..

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          ssh-key: ${{ secrets.PUSH_TO_YEA_SITE }}
          path: target

      - name: Copy build files to target directory
        run: |
          mkdir -p target/${{ env.TARGET_DIR }}
          cp source/${{ env.SOURCE_DIR }}/. target/${{ env.TARGET_DIR }}/ -a

      - name: Commit and push to target repository
        run: |
          cd target
          git config user.email "actions@users.noreply.github.com"
          git config user.name "Automated"
          git add .
          git commit -m "copied from ${{ github.repository }}"
          git push
